;;; pdf-view-pagemark-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from pdf-view-pagemark.el

(autoload 'pdf-view-pagemark-mode "pdf-view-pagemark" "\
Automatically indicate remaining reading position" t)
(register-definition-prefixes "pdf-view-pagemark" '("pdf-view-pagemark"))

;;; End of scraped data

(provide 'pdf-view-pagemark-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pdf-view-pagemark-autoloads.el ends here
